from typing import Dict, Any, List

class ForensicLeadExplainer:
    """
    Computes explainable feature attributions (XAI) for court-admissible dossiers.
    """

    @staticmethod
    def generate_dossier(txid: str, anomaly_score: float, origin_info: Dict[str, Any], is_peeling: bool) -> Dict[str, Any]:
        factors = []
        risk_score = 0.0

        if is_peeling:
            factors.append({"factor": "Recursive Peeling Chain Pattern", "impact": "+35%"})
            risk_score += 35.0

        if origin_info.get("origin_asn") in ["AS205100", "AS14061"]:
            factors.append({"factor": f"Originates from High-Risk Tor/VPN ASN ({origin_info.get('origin_asn')})", "impact": "+30%"})
            risk_score += 30.0

        if anomaly_score > 60:
            factors.append({"factor": f"Statistical Volume/Fee Anomaly (Score {anomaly_score:.1f})", "impact": "+25%"})
            risk_score += 25.0
        else:
            risk_score += anomaly_score * 0.2

        severity = "CRITICAL" if risk_score >= 70 else ("HIGH" if risk_score >= 45 else "LOW")

        return {
            "txid": txid,
            "risk_score": round(min(risk_score, 100.0), 1),
            "severity": severity,
            "origin_ip": origin_info.get("origin_ip"),
            "origin_country": origin_info.get("origin_country"),
            "origin_asn": origin_info.get("origin_asn"),
            "top_contributing_factors": factors,
            "court_admissible_notes": "Generated by VIGIL-CHAIN Offline Forensic Intelligence Suite for NTRO/LEA."
        }
