import hashlib
import json
from typing import Any, Dict, List

import numpy as np

from config.settings import CRITICAL_RISK_THRESHOLD, HIGH_RISK_THRESHOLD, MEDIUM_RISK_THRESHOLD
from src.ml.risk_fusion import ABSENT_LABELS, EVIDENCE_KEYS, EVIDENCE_LABELS

DISCLAIMER = (
    "Investigative lead generated by VIGIL-CHAIN from traffic metadata. Origin attribution "
    "is a statistical estimate and the risk score is a model output: both direct further "
    "inquiry and must be corroborated before being relied on as evidence."
)


def severity_for(risk_score: float) -> str:
    if risk_score >= CRITICAL_RISK_THRESHOLD:
        return "CRITICAL"
    if risk_score >= HIGH_RISK_THRESHOLD:
        return "HIGH"
    if risk_score >= MEDIUM_RISK_THRESHOLD:
        return "MEDIUM"
    return "LOW"


def evidence_hash(record: Dict[str, Any]) -> str:
    """SHA-256 over the canonical JSON form, so any later edit to a dossier is detectable."""
    canonical = json.dumps(record, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


class ForensicLeadExplainer:
    """
    Turns exact Shapley values of the risk-fusion model into explainable dossiers.

    For each lead the log-odds of the risk score is split into one signed contribution
    per evidence signal. Contributions plus the base value reproduce the score exactly;
    `share_pct` is each signal's part of the total upward push, for quick reading.
    """

    @staticmethod
    def factors(evidence_row: np.ndarray, shap_row: np.ndarray, top: int = None) -> List[Dict[str, Any]]:
        push = float(np.sum(np.clip(shap_row, 0.0, None))) or 1.0
        items = []
        for key, value, phi in zip(EVIDENCE_KEYS, evidence_row, shap_row):
            items.append({
                "key": key,
                "factor": ABSENT_LABELS[key] if key in ABSENT_LABELS and value < 0.5 else EVIDENCE_LABELS[key],
                "value": round(float(value), 4),
                "shap_log_odds": round(float(phi), 4),
                "share_pct": round(100.0 * max(float(phi), 0.0) / push, 1),
                "impact": f"{phi:+.2f}",
            })
        items.sort(key=lambda f: abs(f["shap_log_odds"]), reverse=True)
        return items[:top] if top else items

    @staticmethod
    def generate_dossier(tx: Dict[str, Any], risk_score: float, evidence_row: np.ndarray,
                         shap_row: np.ndarray, base_value: float) -> Dict[str, Any]:
        origin = tx.get("_origin", {})
        geo = tx.get("_geo", {})
        factors = ForensicLeadExplainer.factors(evidence_row, shap_row)
        return {
            "txid": tx["txid"],
            "timestamp": tx["_ts"],
            "risk_score": round(float(risk_score), 1),
            "severity": severity_for(risk_score),
            "value_btc": round(sum(tx.get("input_amounts", [])), 8),
            "origin_ip": origin.get("origin_ip"),
            "origin_confidence": origin.get("confidence"),
            "origin_country": geo.get("country"),
            "origin_asn": geo.get("asn"),
            "origin_network": geo.get("category_label"),
            "base_value_log_odds": round(base_value, 4),
            "top_contributing_factors": [f for f in factors if abs(f["shap_log_odds"]) >= 0.01],
            "notes": DISCLAIMER,
        }
